### ISSUE TITLE
PreprocessedExpPipeFactory with BGW Protocol

### ISSUE THREAD

**Issue by p1tach10** [aicis/fresco#118]
I try to run code CompareTest with BGW protocol but there was an error 

```
Error while doing MPC: dk.alexandra.fresco.suite.bgw.BgwFactory cannot be cast to dk.alexandra.fresco.lib.math.integer.exp.PreprocessedExpPipeFactory
java.lang.ClassCastException: dk.alexandra.fresco.suite.bgw.BgwFactory cannot be cast to dk.alexandra.fresco.lib.math.integer.exp.PreprocessedExpPipeFactory
        at org.customcode.compare.CompareDemo.prepareApplication(CompareDemo.java:75)
        at dk.alexandra.fresco.framework.sce.SCEImpl.evalApplication(SCEImpl.java:250)
        at dk.alexandra.fresco.framework.sce.SCEImpl.runApplication(SCEImpl.java:242)
        at org.customcode.compare.CompareDemo.compareDemoMain(CompareDemo.java:164)
        at org.customcode.compare.App.main(App.java:9)
```

**Comment by GuutBoy** [comment]
This essentially means that the BGW implementation does not support the comparison implementation. The BGW implementation has not been very well maintained for a while. Recently, we have been doing a lot of work to restructure the architecture and clean up the framework. As part of this work we have chosen to remove the BGW implementation completely for this exact reason.
