### ISSUE TITLE
crash when noOfVmThreads isn't set in properties, and evaluator is set to Parallel

### ISSUE THREAD

**Issue by Tophwells** [aicis/fresco#30]
If you are experiencing this problem, make sure that `noOfVmThreads` is set in your configuration file, and make sure that it is spelled and capitalised correctly.

This combination of settings crashes FRESCO with an unhelpful exception message. Stack trace:

```
[2016-06-20 18:46:16 +0200] (1) WARNING: Reporter already initialized
NetworkConfigurationImpl [myId=1, parties={1=Party(1, localhost:9001), 2=Party(2, localhost:9002), 3=Party(3, localhost:9003)}, logLevel=INFO]
Exception in thread "main" java.lang.NegativeArraySizeException
    at edu.biu.scapi.comm.multiPartyComm.SocketMultipartyCommunicationSetup.createChannels(SocketMultipartyCommunicationSetup.java:241)
    at edu.biu.scapi.comm.multiPartyComm.SocketMultipartyCommunicationSetup.establishConnections(SocketMultipartyCommunicationSetup.java:195)
    at edu.biu.scapi.comm.multiPartyComm.SocketMultipartyCommunicationSetup.prepareForCommunication(SocketMultipartyCommunicationSetup.java:116)
    at dk.alexandra.fresco.framework.network.ScapiNetworkImpl.connect(ScapiNetworkImpl.java:143)
    at dk.alexandra.fresco.framework.sce.resources.ResourcePoolImpl.initializeNetwork(ResourcePoolImpl.java:108)
    at dk.alexandra.fresco.framework.sce.SCEImpl.setup(SCEImpl.java:154)
    at dk.alexandra.fresco.framework.sce.SCEImpl.runApplication(SCEImpl.java:211)
    at com.tophwells.keycutter.SecurePointAddition.main(SecurePointAddition.java:74)
```

The configuration file I used was:

```
myId = 1
party1 = localhost,9001
party2 = localhost,9002
party3 = localhost,9003
protocolSuite = bgw
evaluator = PARALLEL
storage = IN_MEMORY
noOfThreads = 2
//noOfVmThreads = 2
```

The default value of `noOfVmThreads` is -1, and it silently uses this default if it's not set in the configuration file. Since this value is never checked, it goes straight through to the network code, where it crashes the program when it attempts to create an array of -1 connections to each other player.

We should add a check for this, but I'm not sure where the most natural place is.

**Comment by pffrandsen** [comment]
Closed since these options lo longer are applicable
