### ISSUE TITLE
Error while parsing arguments: Unrecognized option: -vt

### ISSUE THREAD

**Issue by abspoel** [aicis/fresco#330]
When running `make runPrePro` or `make run` in the psi demo, the following error appears in the logs:

```
Exception in thread "main" java.lang.IllegalArgumentException: Error while parsing arguments: Unrecognized option: -vt
        at dk.alexandra.fresco.demo.cli.CmdLineUtil.parse(CmdLineUtil.java:273)
        at dk.alexandra.fresco.demo.PrivateSetDemo.main(PrivateSetDemo.java:109)
Caused by: org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -vt
```

Removing the -vt flag from the Makefile seems to work.

**Comment by GuutBoy** [comment]
I get this as well. Thanks for spotting this. I am afraid the demos have not been maintained so well recently.
