### ISSUE TITLE
Test fails except when run in isolation

### ISSUE THREAD

**Issue by tpj** [aicis/fresco#9]
The test ```dk.alexandra.fresco.suite.spdz.TestSpdzLPSolver3Parties.java``` fails when run with other tests, e.g. when running

    mvn test

or

    mvn test -Dtest=dk.alexandra.fresco.suite.spdz.*

The exception trace is as follows. Note that thread 1+2 fail in ```SpdzNativeProtocol.sendBroadcastValidation``` while thread 3 fails in SpdzMultGate.evaluate. There seems to be some weird dependency between the tests?

```
[2015-12-02 22:00:25 +0100] (285) SEVERE: TestThread(3) threw exception during test:
java.lang.ClassCastException: [B cannot be cast to [Ljava.math.BigInteger;
	at dk.alexandra.fresco.suite.spdz.gates.SpdzMultGate.evaluate(SpdzMultGate.java:140)
	at dk.alexandra.fresco.framework.sce.evaluator.SequentialEvaluator.processBatch(SequentialEvaluator.java:159)
	at dk.alexandra.fresco.framework.sce.evaluator.SequentialEvaluator.doOneRound(SequentialEvaluator.java:116)
	at dk.alexandra.fresco.framework.sce.evaluator.SequentialEvaluator.eval(SequentialEvaluator.java:127)
	at dk.alexandra.fresco.framework.sce.SCEImpl.evalApplication(SCEImpl.java:229)
	at dk.alexandra.fresco.framework.sce.SCEImpl.runApplication(SCEImpl.java:224)
	at dk.alexandra.fresco.lib.arithmetic.LPSolverTests$TestLPSolver$1.test(LPSolverTests.java:138)
	at dk.alexandra.fresco.framework.TestThreadRunner$TestThread.runTest(TestThreadRunner.java:86)
	at dk.alexandra.fresco.framework.TestThreadRunner$TestThread.run(TestThreadRunner.java:74)

[2015-12-02 22:00:25 +0100] (283) SEVERE: TestThread(1) threw exception during test:
java.lang.ClassCastException: [Ljava.math.BigInteger; cannot be cast to [B
	at dk.alexandra.fresco.suite.spdz.gates.SpdzNativeProtocol.receiveBroadcastValidation(SpdzNativeProtocol.java:63)
	at dk.alexandra.fresco.suite.spdz.gates.SpdzCommitGate.evaluate(SpdzCommitGate.java:89)
	at dk.alexandra.fresco.suite.spdz.evaluation.strategy.SpdzProtocolSuite.MACCheck(SpdzProtocolSuite.java:195)
	at dk.alexandra.fresco.suite.spdz.evaluation.strategy.SpdzProtocolSuite.synchronize(SpdzProtocolSuite.java:163)
	at dk.alexandra.fresco.framework.sce.evaluator.SequentialEvaluator.doOneRound(SequentialEvaluator.java:117)
	at dk.alexandra.fresco.framework.sce.evaluator.SequentialEvaluator.eval(SequentialEvaluator.java:127)
	at dk.alexandra.fresco.framework.sce.SCEImpl.evalApplication(SCEImpl.java:229)
	at dk.alexandra.fresco.framework.sce.SCEImpl.runApplication(SCEImpl.java:224)
	at dk.alexandra.fresco.lib.arithmetic.LPSolverTests$TestLPSolver$1.test(LPSolverTests.java:138)
	at dk.alexandra.fresco.framework.TestThreadRunner$TestThread.runTest(TestThreadRunner.java:86)
	at dk.alexandra.fresco.framework.TestThreadRunner$TestThread.run(TestThreadRunner.java:74)

[2015-12-02 22:00:25 +0100] (284) SEVERE: TestThread(2) threw exception during test:
java.lang.ClassCastException: [Ljava.math.BigInteger; cannot be cast to [B
	at dk.alexandra.fresco.suite.spdz.gates.SpdzNativeProtocol.receiveBroadcastValidation(SpdzNativeProtocol.java:63)
	at dk.alexandra.fresco.suite.spdz.gates.SpdzCommitGate.evaluate(SpdzCommitGate.java:89)
	at dk.alexandra.fresco.suite.spdz.evaluation.strategy.SpdzProtocolSuite.MACCheck(SpdzProtocolSuite.java:195)
	at dk.alexandra.fresco.suite.spdz.evaluation.strategy.SpdzProtocolSuite.synchronize(SpdzProtocolSuite.java:163)
	at dk.alexandra.fresco.framework.sce.evaluator.SequentialEvaluator.doOneRound(SequentialEvaluator.java:117)
	at dk.alexandra.fresco.framework.sce.evaluator.SequentialEvaluator.eval(SequentialEvaluator.java:127)
	at dk.alexandra.fresco.framework.sce.SCEImpl.evalApplication(SCEImpl.java:229)
	at dk.alexandra.fresco.framework.sce.SCEImpl.runApplication(SCEImpl.java:224)
	at dk.alexandra.fresco.lib.arithmetic.LPSolverTests$TestLPSolver$1.test(LPSolverTests.java:138)
	at dk.alexandra.fresco.framework.TestThreadRunner$TestThread.runTest(TestThreadRunner.java:86)
	at dk.alexandra.fresco.framework.TestThreadRunner$TestThread.run(TestThreadRunner.java:74)
```

**Comment by tpj** [comment]
@Rhaea: Can you reproduce the exception? E.g., by running

    mvn test -Dtest=dk.alexandra.fresco.suite.spdz.*

**Comment by Rhaea** [comment]
Yup – men forstår ikke helt hvorfor det sker. Og har ikke tid til at se på det.
Men det er helt sikkert noget med storage som af en eller anden grund ikke er sat rigtigt op. Måske noget med FakeTripGen der holder nogen statiske variable som muligvis bliver sat i 2-party tilfældet, og så går noget galt ved 3-party testen.
--
_____________________________________________

KASPER DAMGÅRD

FORSKNINGS- OG INNOVATIONSSPECIALIST
SECURITY LAB

RESEARCH AND INNOVATIONSPECIALIST
SECURITY LAB

ALEXANDRA INSTITUTTET A/S
THE ALEXANDRA INSTITUTE LTD.

T   +45 30 55 33 86
W  www.alexandra.dk<http://www.alexandra.dk/>
__________________________________________

**Comment by GuutBoy** [comment]
Looks very strange. Apparently player 3 thinks we are doing a multiplication while the other parties are doing a commitment. Somehow they are getting out of sync. I doubt this has to do with the preprocessed triples.

**Comment by GuutBoy** [comment]
Ok, I think I found the problem. Players 1 and 2 are going into MACCheck-mode while Player 3 goes on computing. The problem is that the gatesEvaluated variable is not reset between tests. So after doing a test with 2 players, in a test with 3 players Player 3 is going to be out of sync with the other two players.

**Comment by Rhaea** [comment]
Well spotted!
--
_____________________________________________

KASPER DAMGÅRD

FORSKNINGS- OG INNOVATIONSSPECIALIST
SECURITY LAB

RESEARCH AND INNOVATIONSPECIALIST
SECURITY LAB

ALEXANDRA INSTITUTTET A/S
THE ALEXANDRA INSTITUTE LTD.

T   +45 30 55 33 86
W  www.alexandra.dk<http://www.alexandra.dk/>
__________________________________________

**Comment by GuutBoy** [comment]
Thank you! It took a while to find as well. In the end it is a one line fix (reset the variable when done evaluating). However, they may be other issues related to this (some other state may not be reset).

BTW @Rhaea, could you maybe not include your signature and previous emails in these conversations? It looks very odd on github.
